<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fund Transfer Report - Print Preview</title>
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            font-family: 'Public Sans', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            color: #1e293b;
            background: #f8fafc;
            padding: 20px;
            font-size: 11px;
        }

        .report-header {
            border-bottom: 2px solid #0f6698;
            padding-bottom: 12px;
            margin-bottom: 15px;
        }

        .report-title {
            color: #0f6698;
            font-weight: 700;
            font-size: 1.25rem;
            text-transform: uppercase;
            margin: 0;
        }

        .badge-filter {
            background-color: #f1f5f9;
            color: #475569;
            border: 1px solid #cbd5e1;
            padding: 2px 8px;
            border-radius: 4px;
            font-size: 11px;
            display: inline-block;
            margin-right: 6px;
        }

        table.print-table {
            width: 100%;
            border-collapse: collapse;
            font-size: 10px;
        }

        table.print-table th {
            background-color: #f1f5f9 !important;
            color: #334155;
            font-weight: 700;
            text-transform: uppercase;
            border: 1px solid #cbd5e1;
            padding: 5px 6px;
            white-space: nowrap;
        }

        table.print-table td {
            border: 1px solid #e2e8f0;
            padding: 4px 6px;
            vertical-align: middle;
        }

        table.print-table tr:nth-child(even) td {
            background-color: #f8fafc;
        }

        .no-print-bar {
            background: #ffffff;
            border: 1px solid #cbd5e1;
            border-radius: 8px;
            padding: 10px 15px;
            margin-bottom: 20px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.05);
        }

        .total-summary-box {
            width: 220px;
            border: 1px solid #cbd5e1;
            background: #ffffff;
            padding: 8px 12px;
            border-radius: 6px;
            font-family: monospace;
            font-size: 11px;
        }

        @media print {
            body {
                background: #ffffff;
                padding: 0;
                font-size: 9px;
            }
            .no-print {
                display: none !important;
            }
            table.print-table th {
                background-color: #e2e8f0 !important;
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
            }
            table.print-table td {
                padding: 3px 4px;
            }
            @page {
                size: landscape;
                margin: 8mm;
            }
        }
    </style>
</head>
<body>

    {{-- Top Action Bar (Hidden during print) --}}
    <div class="no-print-bar no-print d-flex justify-content-between align-items-center">
        <div>
            <strong class="text-primary fs-6">Fund Transfer Report - Print Preview</strong>
            <div class="text-muted small">Total {{ count($transfers) }} records found</div>
        </div>
        <div class="d-flex gap-2">
            <button class="btn btn-primary btn-sm px-4 fw-bold" onclick="window.print()">
                🖨️ Print Report
            </button>
            <button class="btn btn-secondary btn-sm px-3" onclick="window.close()">
                ✖ Close
            </button>
        </div>
    </div>

    {{-- Report Header --}}
    <div class="report-header">
        <div class="d-flex justify-content-between align-items-start">
            <div>
                <h1 class="report-title">SMS Gateway — Fund Transfer Details Report</h1>
                <div class="text-secondary small mt-1">Generated by Admin Panel | Total Transactions: <strong>{{ count($transfers) }}</strong></div>
            </div>
            <div class="text-end small text-secondary">
                <div><strong>Printed On:</strong> {{ date('d/m/Y h:i A') }}</div>
            </div>
        </div>

        {{-- Applied Filters Bar --}}
        <div class="mt-2 pt-2 border-top">
            <span class="fw-bold small text-dark me-2">Applied Filters:</span>
            @if(!empty($filters['from_date']) || !empty($filters['to_date']))
                <span class="badge-filter"><strong>Date Range:</strong> {{ $filters['from_date'] ?? 'Start' }} to {{ $filters['to_date'] ?? 'End' }}</span>
            @else
                <span class="badge-filter"><strong>Date Range:</strong> All Dates</span>
            @endif

            @if(!empty($filters['company_name']))
                <span class="badge-filter"><strong>Company:</strong> {{ $filters['company_name'] }}</span>
            @endif

            @if(!empty($filters['user_name']))
                <span class="badge-filter"><strong>User Name:</strong> {{ $filters['user_name'] }}</span>
            @endif

            @if(!empty($filters['reg_no']))
                <span class="badge-filter"><strong>Reg No:</strong> {{ $filters['reg_no'] }}</span>
            @endif

            @if(!empty($filters['trans_desc']))
                <span class="badge-filter"><strong>Desc:</strong> {{ $filters['trans_desc'] }}</span>
            @endif
        </div>
    </div>

    {{-- Data Table --}}
    <table class="table print-table">
        <thead>
            <tr>
                <th style="width:30px;" class="text-center">#</th>
                <th class="text-center">REG NO</th>
                <th>COMPANY NAME</th>
                <th class="text-center">REQUEST TYPE</th>
                <th class="text-center">TRANSFER TYPE</th>
                <th class="text-end">TRANSFER AMOUNT</th>
                <th class="text-end">OPENING BALANCE</th>
                <th class="text-end">CLOSING BALANCE</th>
                <th class="text-center">WALLET TYPE</th>
                <th>TRANSACTION DESC</th>
                <th class="text-center">TRANSACTION ID</th>
                <th class="text-center">TRANSACTION DATE/TIME</th>
                <th class="text-center">REQUEST ID</th>
                <th class="text-center">INSERT DATE</th>
            </tr>
        </thead>
        <tbody>
            @forelse($transfers as $index => $t)
                @php
                    $company = $t->user->company_name ?? '-';
                    $reqType = (string)$t->reqtype === '0' ? 'BY ADMIN' : 'BY USER';
                    $transType = (string)$t->transfertype === '1' ? 'FUND TRANSFER' : 'FUND REVERSE';
                    $walletType = $t->walletType->typename ?? ($t->wallet_type_id == 1 ? 'PREPAID BALANCE' : '-');
                    $transDateTime = ($t->trans_date ? date('d/m/Y', strtotime($t->trans_date)) : '') . ' ' . ($t->trans_time ?? '');
                @endphp
                <tr>
                    <td class="text-center text-muted fw-bold">{{ $index + 1 }}</td>
                    <td class="text-center font-monospace fw-bold">{{ $t->regno ?? '-' }}</td>
                    <td class="fw-semibold">{{ $company }}</td>
                    <td class="text-center">{{ $reqType }}</td>
                    <td class="text-center">{{ $transType }}</td>
                    <td class="text-end fw-bold font-monospace">{{ number_format((float)$t->transfer_amt, 2) }}</td>
                    <td class="text-end font-monospace">{{ number_format((float)$t->opening_bal, 2) }}</td>
                    <td class="text-end fw-bold text-success font-monospace">{{ number_format((float)$t->closing_bal, 2) }}</td>
                    <td class="text-center">{{ $walletType }}</td>
                    <td>{{ $t->transdesc ?: '-' }}</td>
                    <td class="text-center font-monospace">{{ $t->online_tranid ?: '-' }}</td>
                    <td class="text-center text-nowrap">{{ trim($transDateTime) ?: '-' }}</td>
                    <td class="text-center font-monospace">{{ $t->request_id ?: '-' }}</td>
                    <td class="text-center text-nowrap">{{ $t->insert_date ?? '-' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="14" class="text-center py-4 text-muted">No fund transfer records found for the selected criteria.</td>
                </tr>
            @endforelse
        </tbody>
        <tfoot>
            <tr style="background:#f8fafc; border-top:2px solid #cbd5e1;">
                <td colspan="5" style="text-align:right; font-weight:bold; padding-right:10px; vertical-align:top; font-size:11px;">
                    TOTAL
                </td>
                <td style="padding:4px; vertical-align:top;">
                    <table style="width:100%; min-width:130px; font-size:10px; font-family:monospace; border:1px solid #cbd5e1; background:#ffffff;">
                        <tr>
                            <td style="padding:2px 4px; text-align:left;">PREPAID</td>
                            <td>:</td>
                            <td style="text-align:right; font-weight:bold; padding:2px 4px;">{{ number_format((float)$prepaidTotal, 2) }}</td>
                        </tr>
                        <tr>
                            <td style="padding:2px 4px; text-align:left;">UTILITY</td>
                            <td>:</td>
                            <td style="text-align:right; font-weight:bold; padding:2px 4px;">{{ number_format((float)$utilityTotal, 2) }}</td>
                        </tr>
                        <tr>
                            <td style="padding:2px 4px; text-align:left;">BANK</td>
                            <td>:</td>
                            <td style="text-align:right; font-weight:bold; padding:2px 4px;">{{ number_format((float)$bankTotal, 2) }}</td>
                        </tr>
                        <tr style="border-top:1px solid #cbd5e1;">
                            <td style="padding:2px 4px; font-weight:bold; text-align:left;">TOTAL</td>
                            <td>:</td>
                            <td style="text-align:right; font-weight:bold; color:#0f6698; padding:2px 4px;">{{ number_format((float)$grandTotal, 2) }}</td>
                        </tr>
                    </table>
                </td>
                <td colspan="8"></td>
            </tr>
        </tfoot>
    </table>

    <script>
        window.addEventListener('load', () => {
            setTimeout(() => {
                window.print();
            }, 600);
        });
    </script>
</body>
</html>
