<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SMS Live Panel Report - Print Preview</title>
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            font-family: 'Public Sans', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            color: #1e293b;
            background: #f8fafc;
            padding: 20px;
            font-size: 11px;
        }

        .report-header {
            border-bottom: 2px solid #0f6698;
            padding-bottom: 12px;
            margin-bottom: 15px;
        }

        .report-title {
            color: #0f6698;
            font-weight: 700;
            font-size: 1.25rem;
            text-transform: uppercase;
            margin: 0;
        }

        .badge-filter {
            background-color: #f1f5f9;
            color: #475569;
            border: 1px solid #cbd5e1;
            padding: 2px 8px;
            border-radius: 4px;
            font-size: 11px;
            display: inline-block;
            margin-right: 6px;
        }

        table.print-table {
            width: 100%;
            border-collapse: collapse;
            font-size: 10px;
        }

        table.print-table th {
            background-color: #f1f5f9 !important;
            color: #334155;
            font-weight: 700;
            text-transform: uppercase;
            border: 1px solid #cbd5e1;
            padding: 5px 6px;
            white-space: nowrap;
        }

        table.print-table td {
            border: 1px solid #e2e8f0;
            padding: 4px 6px;
            vertical-align: top;
        }

        table.print-table tr:nth-child(even) td {
            background-color: #f8fafc;
        }

        .sms-text-print {
            white-space: normal !important;
            word-break: break-word;
            line-height: 1.4;
            max-width: 320px;
            color: #0f172a;
            font-size: 10px;
        }

        .no-print-bar {
            background: #ffffff;
            border: 1px solid #cbd5e1;
            border-radius: 8px;
            padding: 10px 15px;
            margin-bottom: 20px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.05);
        }

        @media print {
            body {
                background: #ffffff;
                padding: 0;
                font-size: 9px;
            }
            .no-print {
                display: none !important;
            }
            table.print-table th {
                background-color: #e2e8f0 !important;
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
            }
            table.print-table td {
                padding: 3px 4px;
            }
            @page {
                size: landscape;
                margin: 8mm;
            }
        }
    </style>
</head>
<body>

    {{-- Top Action Bar (Hidden during print) --}}
    <div class="no-print-bar no-print d-flex justify-content-between align-items-center">
        <div>
            <strong class="text-primary fs-6">SMS Live Panel - Print Preview</strong>
            <div class="text-muted small">Total {{ count($transactions) }} transactions found</div>
        </div>
        <div class="d-flex gap-2">
            <button class="btn btn-primary btn-sm px-4 fw-bold" onclick="window.print()">
                🖨️ Print Report
            </button>
            <button class="btn btn-secondary btn-sm px-3" onclick="window.close()">
                ✖ Close
            </button>
        </div>
    </div>

    {{-- Report Header --}}
    <div class="report-header">
        <div class="d-flex justify-content-between align-items-start">
            <div>
                <h1 class="report-title">SMS Gateway — Live SMS Details Report</h1>
                <div class="text-secondary small mt-1">Generated by Admin Panel | Total Transactions: <strong>{{ count($transactions) }}</strong></div>
            </div>
            <div class="text-end small text-secondary">
                <div><strong>Printed On:</strong> {{ date('d/m/Y h:i A') }}</div>
            </div>
        </div>

        {{-- Applied Filters Bar --}}
        <div class="mt-2 pt-2 border-top">
            <span class="fw-bold small text-dark me-2">Applied Filters:</span>
            @if(!empty($filters['from_date']) || !empty($filters['to_date']))
                <span class="badge-filter"><strong>Date Range:</strong> {{ $filters['from_date'] ?? 'Start' }} to {{ $filters['to_date'] ?? 'End' }}</span>
            @else
                <span class="badge-filter"><strong>Date Range:</strong> All Dates</span>
            @endif

            @if(!empty($filters['tran_id']))
                <span class="badge-filter"><strong>Tran ID:</strong> {{ $filters['tran_id'] }}</span>
            @endif

            @if(!empty($filters['recharge_no']))
                <span class="badge-filter"><strong>Recharge No:</strong> {{ $filters['recharge_no'] }}</span>
            @endif

            @if(!empty($filters['operator_name']))
                <span class="badge-filter"><strong>Operator:</strong> {{ $filters['operator_name'] }}</span>
            @endif

            @if(!empty($filters['user_name']))
                <span class="badge-filter"><strong>User:</strong> {{ $filters['user_name'] }}</span>
            @endif
        </div>
    </div>

    {{-- Data Table --}}
    <table class="table print-table">
        <thead>
            <tr>
                <th style="width:30px;" class="text-center">#</th>
                <th>TRAN ID</th>
                <th style="min-width: 250px;">SMS TEXT</th>
                <th class="text-center">SENDER ID</th>
                <th class="text-center">ENTITY ID</th>
                <th class="text-center">SEND TO</th>
                <th class="text-center">STATUS</th>
                <th class="text-center">CREDIT USE</th>
                <th class="text-end">CHARGES</th>
                <th class="text-center">TRAN DATE/TIME</th>
                <th>USER DETAILS</th>
            </tr>
        </thead>
        <tbody>
            @forelse($transactions as $index => $t)
                @php
                    $userName = $t->user ? trim(($t->user->fname ?? '') . ' ' . ($t->user->lname ?? '')) : '-';
                    $company = $t->user ? ($t->user->company_name ?? '-') : '-';
                    $statusStr = (string)$t->status === '1' ? 'SUCCESS' : ((string)$t->status === '2' ? 'FAILED' : 'PENDING');
                    $statusClass = (string)$t->status === '1' ? 'text-success fw-bold' : ((string)$t->status === '2' ? 'text-danger fw-bold' : 'text-warning');
                    $transDateTime = ($t->trandate ? date('d/m/Y', strtotime($t->trandate)) : '') . ' ' . ($t->trantime ?? '');
                @endphp
                <tr>
                    <td class="text-center text-muted fw-bold">{{ $index + 1 }}</td>
                    <td class="font-monospace fw-bold">{{ $t->servid ?? '-' }}</td>
                    <td>
                        <div class="sms-text-print">
                            {{ $t->smstext ?? $t->msg ?? '-' }}
                        </div>
                    </td>
                    <td class="text-center font-monospace">{{ $t->sender_id ?? '-' }}</td>
                    <td class="text-center font-monospace">{{ $t->template_id ?? $t->entityid ?? '-' }}</td>
                    <td class="text-center font-monospace fw-bold">{{ $t->rechargeno ?? '-' }}</td>
                    <td class="text-center {{ $statusClass }}">{{ $statusStr }}</td>
                    <td class="text-center font-monospace">{{ $t->credit_count ?? $t->credit_use ?? 1 }}</td>
                    <td class="text-end font-monospace">{{ number_format((float)($t->amount ?? $t->sms_charge ?? 0), 2) }}</td>
                    <td class="text-center text-nowrap">{{ trim($transDateTime) ?: '-' }}</td>
                    <td>
                        <div class="fw-semibold">{{ $userName }}</div>
                        <div class="text-muted" style="font-size: 9px;">{{ $company }}</div>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="11" class="text-center py-4 text-muted">No SMS records found for the selected criteria.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <script>
        window.addEventListener('load', () => {
            setTimeout(() => {
                window.print();
            }, 600);
        });
    </script>
</body>
</html>
