<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Details Report - Print Preview</title>
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            font-family: 'Public Sans', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            color: #1e293b;
            background: #f8fafc;
            padding: 20px;
            font-size: 11px;
        }

        .report-header {
            border-bottom: 2px solid #0f6698;
            padding-bottom: 12px;
            margin-bottom: 15px;
        }

        .report-title {
            color: #0f6698;
            font-weight: 700;
            font-size: 1.25rem;
            text-transform: uppercase;
            margin: 0;
        }

        .badge-filter {
            background-color: #f1f5f9;
            color: #475569;
            border: 1px solid #cbd5e1;
            padding: 2px 8px;
            border-radius: 4px;
            font-size: 11px;
            display: inline-block;
            margin-right: 6px;
        }

        table.print-table {
            width: 100%;
            border-collapse: collapse;
            font-size: 10px;
        }

        table.print-table th {
            background-color: #f1f5f9 !important;
            color: #334155;
            font-weight: 700;
            text-transform: uppercase;
            border: 1px solid #cbd5e1;
            padding: 5px 6px;
            white-space: nowrap;
        }

        table.print-table td {
            border: 1px solid #e2e8f0;
            padding: 4px 6px;
            vertical-align: middle;
        }

        table.print-table tr:nth-child(even) td {
            background-color: #f8fafc;
        }

        .no-print-bar {
            background: #ffffff;
            border: 1px solid #cbd5e1;
            border-radius: 8px;
            padding: 10px 15px;
            margin-bottom: 20px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.05);
        }

        @media print {
            body {
                background: #ffffff;
                padding: 0;
                font-size: 9px;
            }
            .no-print {
                display: none !important;
            }
            table.print-table th {
                background-color: #e2e8f0 !important;
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
            }
            table.print-table td {
                padding: 3px 4px;
            }
            @page {
                size: landscape;
                margin: 8mm;
            }
        }
    </style>
</head>
<body>

    {{-- Top Action Bar (Hidden during print) --}}
    <div class="no-print-bar no-print d-flex justify-content-between align-items-center">
        <div>
            <strong class="text-primary fs-6">User Details Report - Print Preview</strong>
            <div class="text-muted small">Total {{ count($users) }} records found</div>
        </div>
        <div class="d-flex gap-2">
            <button class="btn btn-primary btn-sm px-4 fw-bold" onclick="window.print()">
                🖨️ Print Report
            </button>
            <button class="btn btn-secondary btn-sm px-3" onclick="window.close()">
                ✖ Close
            </button>
        </div>
    </div>

    {{-- Report Header --}}
    <div class="report-header">
        <div class="d-flex justify-content-between align-items-start">
            <div>
                <h1 class="report-title">SMS Gateway — User Details Report</h1>
                <div class="text-secondary small mt-1">Generated by Admin Panel | Total Records: <strong>{{ count($users) }}</strong></div>
            </div>
            <div class="text-end small text-secondary">
                <div><strong>Printed On:</strong> {{ date('d/m/Y h:i A') }}</div>
            </div>
        </div>

        {{-- Applied Filters Bar --}}
        <div class="mt-2 pt-2 border-top">
            <span class="fw-bold small text-dark me-2">Applied Filters:</span>
            @if(!empty($filters['from_date']) || !empty($filters['to_date']))
                <span class="badge-filter"><strong>Date Range:</strong> {{ $filters['from_date'] ?? 'Start' }} to {{ $filters['to_date'] ?? 'End' }}</span>
            @else
                <span class="badge-filter"><strong>Date Range:</strong> All Dates</span>
            @endif

            @if(!empty($filters['user_name']))
                <span class="badge-filter"><strong>User Name / Regno:</strong> {{ $filters['user_name'] }}</span>
            @endif

            @if(!empty($filters['contact_no']))
                <span class="badge-filter"><strong>Contact:</strong> {{ $filters['contact_no'] }}</span>
            @endif

            @if(!empty($filters['quick_search']))
                <span class="badge-filter"><strong>Quick Search:</strong> {{ $filters['quick_search'] }}</span>
            @endif
        </div>
    </div>

    {{-- Data Table --}}
    <table class="table print-table">
        <thead>
            <tr>
                <th style="width:30px;" class="text-center">#</th>
                <th class="text-center">REG NO</th>
                <th>USER NAME</th>
                <th>USER TYPE</th>
                <th>COMPANY NAME</th>
                <th>CONTACT NUMBER</th>
                <th>EMAIL ID</th>
                <th>PACKAGE</th>
                <th class="text-end">BALANCE</th>
                <th>PIN</th>
                <th>PAN NO</th>
                <th>GST NUMBER</th>
                <th>AADHAAR</th>
                <th class="text-center">OTP</th>
                <th>USER ID</th>
                <th>IP WHITELIST</th>
                <th class="text-center">STATUS</th>
                <th class="text-center">REG DATE</th>
            </tr>
        </thead>
        <tbody>
            @forelse($users as $index => $u)
                @php
                    $fullName = trim(($u->fname ?? '') . ' ' . ($u->lname ?? ''));
                    $userType = $u->userType->user_name ?? ($u->catid ? 'TYPE ' . $u->catid : 'API USER');
                    $packageName = $u->package->pack_name ?? ($u->package_id ? 'PLAN #' . $u->package_id : '-');
                    $totalBalance = $u->balanceSheet->balance_amt ?? $u->balanceSheet->total_amt_for_prepaid ?? $u->regamt ?? '0.00';
                    $statusStr = in_array(strtoupper((string)$u->status), ['1', 'ACTIVE']) ? 'ACTIVE' : 'INACTIVE';
                    $isOtp = in_array(strtoupper((string)$u->isotpverify), ['1', 'YES']) ? 'YES' : 'NO';
                @endphp
                <tr>
                    <td class="text-center text-muted fw-bold">{{ $index + 1 }}</td>
                    <td class="text-center font-monospace fw-bold">{{ $u->regno ?? '-' }}</td>
                    <td class="fw-bold">{{ $fullName ?: ('User #' . $u->id) }}</td>
                    <td>{{ $userType }}</td>
                    <td>{{ $u->company_name ?? '-' }}</td>
                    <td class="font-monospace">{{ $u->phone ?? '-' }}</td>
                    <td>{{ $u->email ?? '-' }}</td>
                    <td>{{ $packageName }}</td>
                    <td class="text-end fw-bold font-monospace">{{ number_format((float)$totalBalance, 2) }}</td>
                    <td class="font-monospace">{{ $u->pincode ?? '-' }}</td>
                    <td class="font-monospace">{{ $u->panno ?? '-' }}</td>
                    <td class="font-monospace">{{ $u->gstnumber ?? '-' }}</td>
                    <td class="font-monospace">{{ $u->aadharno ?? '-' }}</td>
                    <td class="text-center">{{ $isOtp }}</td>
                    <td class="font-monospace">{{ $u->userid ?? ('USR' . ($u->regno ?? '')) }}</td>
                    <td class="font-monospace">{{ $u->ipaddress ?? '*' }}</td>
                    <td class="text-center fw-bold {{ $statusStr === 'ACTIVE' ? 'text-success' : 'text-danger' }}">{{ $statusStr }}</td>
                    <td class="text-center text-nowrap">{{ $u->regst_date ?? $u->insert_date ?? '-' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="18" class="text-center py-4 text-muted">No user records found for the selected criteria.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <script>
        window.addEventListener('load', () => {
            // Auto open print dialog if directly loaded
            setTimeout(() => {
                window.print();
            }, 600);
        });
    </script>
</body>
</html>
